### PR TITLE
Get position and update get result

### PR DESCRIPTION
**Pull request by saineti**

### CODE REVIEW

**Comment by saineti** [comment]
This branch can be successfully merged with indigo-devel. However, the travis-ci test fails with the message that the file in #include "code_it_msgs/GetPositionAction.h" does not exist. We believe this is because the branch does not automatically generate messages for newly added primitives. We merged our code_it_msgs branch into the main branch, so the action primitive exists and the code works on our local machines. Is it fine if we merge this branch with the failed test?

**Comment by saineti** [comment]
We are now getting this error when the travis-ci runs:

> The command "sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool 
    ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros" failed and exited with 100 during .

The only modification we made is to the robot_api.cpp file, in which we rounded position values to have 3 decimal places, so we don't know where this error is coming from.

**Comment by jstnhuang** [comment]
As you pointed out, the build is failing while trying to install catkin and other stuff. If you look carefully at the Travis output, it seems to be python-catkin-pkg that is the problem.

Try to fix the build. Perhaps `python-catkin-pkg` is not even necessary, so see what happens when you remove it. To do this, edit the `.travis.yml` file and push your changes. This file holds the list of commands that the Travis CI virtual machine runs for every push. Oftentimes, it can take a few tries to get the build working again. As a last resort, you can just push your changes to indigo-devel anyway.

**Comment by saineti** [comment]
Thank you for the response! As per your suggestion, we removed the python-catkin-pkg line from the .travis.yml file, however the build still failed, as the lines right below this one started to fail. We tried the same approach on the next two lines with no success.
Additionally, we re-ran a previous build that had passed and now that build is failing as well, so we suspect that somewhere a dependency has changed, but we don't know how to pinpoint what that change might be.
Do you have any suggestions?

**Comment by indigok** [comment]
Hi Justin! Travis CI just passed on our last commit, and didn't get the installation errors after we merged it with Lily and Luna's merged branch. We're not sure why this affected Travis CI and would still appreciate any insight you might have but for now we'll merge this branch!

**Pull request merged**
